### ISSUE TITLE
No conversion for float types?

### ISSUE THREAD

**Issue by zimond** [bluejekyll/pg-extend-rs#98]
Is there a way to use params other than integers and strings? like `f64` or `f32` or `bool`? I'm pretty new to postgres, please forgive me if this is a dumb question.

**Comment by bluejekyll** [comment]
To support floating point numbers, there are a few options: https://www.postgresql.org/docs/12/datatype-numeric.html#DATATYPE-FLOAT

To support this, we'll need some conversions like the i64 conversions: https://github.com/bluejekyll/pg-extend-rs/blob/master/pg-extend/src/pg_datum.rs#L125-L151

I haven't looked at the internal Datum representation in PG for this yet, but I think that's pretty much the work, needed.

**Comment by bluejekyll** [comment]
There are a whole bunch of `pg_extend::pg_sys::float*` functions that look like the things that would need to be investigated for transforming from platform data types to datum. Someone will need to investigate the properly methods to use for those conversions.

**Comment by zimond** [comment]
Thanks. I'll try to add something

**Comment by eeeebbbbrrrr** [comment]
I'm no expert here, but it seems to me that since the rust extension is going to be running on the same physical host as postgres, so the raw bytes in memory ought to just be castable to Rust's float types.

Don't quote me on this -- unless it turns out to be correct.

And you can always use Postgres' `floatNout()` functions to validate tests by comparing string forms.

**Comment by bluejekyll** [comment]
If that's the case, then this should be able to be identical to the way we do i32 and i64 conversions, take a look at `datum.rs`
